<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta http-equiv="x-ua-compatible" content="ie=edge" />
	<title>Material Design for Bootstrap</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
	<!-- Google Fonts Roboto -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
	<!-- MDB -->
	<link rel="stylesheet" href="assets/front/css/mdb.min.css" />
	<!-- Custom styles -->
	
	<link rel="stylesheet" href="assets/front/css/fileNotFound.css" />
	<link rel="stylesheet" href="assets/front/css/style.css" />

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>

<body>
	<header>
		<!-- Intro settings -->
		<style>
			#intro {
				/* Margin to fix overlapping fixed navbar */
				margin-top: 58px;
			}

			@media (max-width: 991px) {
				#intro {
					/* Margin to fix overlapping fixed navbar */
					margin-top: 45px;
				}
			}
		</style>

		<!-- Navbar -->
		<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
			<div class="container-fluid">
				<!-- Navbar brand -->
				<a class="navbar-brand" href="/">
					<img class="logo-img" src="assets/front/img/logoCNCVerse.svg" height="32" alt="" loading="lazy" style="margin-top: -3px;" />
				</a>
				<button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
					<i class="fas fa-bars"></i>
				</button>
				<div class="collapse navbar-collapse" id="navbarExample01">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item active">
							<a class="nav-link" aria-current="page" href="/">Inicio</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/categorias" rel="nofollow">Categorias</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/admin">Entrar</a>
						</li>
					</ul>

					<form action="/pesquisar" method="POST" enctype="multipart/form-data" class="d-flex" role="search">
						<input class="form-control me-2" name="search" type="search" placeholder="Pesquisar" aria-label="Search" required>
						<button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
					</form>

					<!-- <ul class="navbar-nav d-flex flex-row">
						
						<li class="nav-item me-3 me-lg-0">
							<a class="nav-link" href="#" rel="nofollow">
								<i class="fab fa-youtube"></i>
							</a>
						</li>
						<li class="nav-item me-3 me-lg-0">
							<a class="nav-link" href="#" rel="nofollow">
								<i class="fab fa-facebook-f"></i>
							</a>
						</li>
						<li class="nav-item me-3 me-lg-0">
							<a class="nav-link" href="#" rel="nofollow">
								<i class="fab fa-twitter"></i>
							</a>
						</li>
						<li class="nav-item me-3 me-lg-0">
							<a class="nav-link" href="#" rel="nofollow">
								<i class="fab fa-github"></i>
							</a>
						</li>
					</ul> -->
				</div>
			</div>
		</nav>
		<!-- Navbar -->

		<!-- Jumbotron -->
		<div id="intro" class="p-5 text-center bg-light">
			<h1 class="mb-3 h2">Um universo de arquivos para cortes em CNC Laser e Router</h1>
			<p class="mb-3">Em algum multiverso desse sistema o seu arquivo está</p>
			<!-- <a class="btn btn-primary m-2" href="#" role="button" rel="nofollow"
        >Buscar</a> -->
			<a class="btn btn-primary m-2" href="#" role="button">Pesquisar</a>
		</div>
		<!-- Jumbotron -->
	</header>
	<!--Main Navigation-->

	<!--Main layout-->
	<main class="my-5">
		<div class="container">
			<!--Section: Content-->
			<?php $this->content(); ?>
			<!--Section: Content-->

			<!-- Pagination -->

		</div>
	</main>
	<!--Main layout-->

	<!--Footer-->
	<footer class="bg-light text-lg-start">
		<!-- <div class="py-4 text-center">
      <a role="button" class="btn btn-primary btn-lg m-2"
        href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow" >
        Learn Bootstrap 5
      </a>
      <a role="button" class="btn btn-primary btn-lg m-2" href="https://mdbootstrap.com/docs/standard/" >
        Download MDB UI KIT
      </a>
    </div> -->

		<hr class="m-0" />

		<div class="text-center py-4 align-items-center">
			<p>Me siga nas redes sociais</p>
			<a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
				<i class="fab fa-youtube"></i>
			</a>
			<a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
				<i class="fab fa-facebook-f"></i>
			</a>
			<a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
				<i class="fab fa-twitter"></i>
			</a>
			<a href="#" class="btn btn-primary m-1" role="button" rel="nofollow">
				<i class="fab fa-github"></i>
			</a>
		</div>

		<!-- Copyright -->
		<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
			© 2023 Copyright:
			<a class="text-dark" href="https://mdbootstrap.com/">Fábio Eduardo Faria</a>
		</div>
		<!-- Copyright -->
	</footer>
	<!--Footer-->
	<!-- MDB -->
	<script type="text/javascript" src="assets/front/js/mdb.min.js"></script>
	<!-- Custom scripts -->
	<!-- <script type="text/javascript" src="assets/front/js/script.js"></script> -->

	<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>

	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js" integrity="sha512-zMfrMAZYAlNClPKjN+JMuslK/B6sPM09BGvrWlW+cymmPmsUT1xJF3P4kxI3lOh9zypakSgWaTpY6vDJY/3Dig==" crossorigin="anonymous"></script>

	<script src="assets/front/js/easing.js" type="text/javascript"></script>


	<script>
		function toTop(pagina) {
			$('html, body').animate({
				scrollTop: 0
			}, 800, 'easeOutQuart');

			// alert('a paginação a ser aberta é ' + pagina)



			setTimeout(function() {
				window.location.href = "?pagina=" + pagina;
			}, 1000);
		}
	</script>

</body>

</html>